### ISSUE TITLE
in app browser plugin dependency should specify version, not latest from repo

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/cordova-plugin-appmobi#1]
Currently the cordova-plugin-inappbrowser plugin dependency points to the latest version in master, which will be a dev version:
<dependency id="cordova-plugin-inappbrowser" url="https://github.com/apache/cordova-plugin-inappbrowser.git" />

This could result in instability for end-users.
It would be better to point to a specific version or to the latest released version.
The former could be done by specifying a tag gitref for the url; the latter could be done by only specifying the id and not specifying the url.
Refer to cordova plugin docs:
https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html

**Comment by inderpreet-singh** [comment]
We posted an issue - https://issues.apache.org/jira/browse/CB-10040 in InAppBrowser plugin whose fix was updated on Git/master not npm. So, we were recommended to use master branch of Git(<dependency id="cordova-plugin-inappbrowser" url="https://github.com/apache/cordova-plugin-inappbrowser.git" />) instead of NPM(<dependency id="cordova-plugin-inappbrowser" />) for now.

We checked the other branches of InAppBrowser plugin repository but it seems this fix is currently available in Master branch only. Once fix is available in npm we will update the dependency tag to direct it to the NPM instead of Git.

**Comment by tony--** [comment]
Thanks for explaining, I see [the recommendation on the JIRA](https://issues.apache.org/jira/browse/CB-10040?focusedCommentId=15015630&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15015630).  It makes sense, but pointing to HEAD of the master branch is dangerous because it can be changed at any time, possibly introducing stability issues for users.  There are a couple ways you could address this.
1. Instead of pointing to HEAD, point to a gitref for a specific commit, such as [this one](https://github.com/apache/cordova-plugin-inappbrowser/commit/542536f7908a776ec49becb0bf40969ee4a48a82).
2. Another option would be to fork the repo and (temporarily) point to your fork instead of to the HEAD of the cordova repo.  In this option you would avoid making any destabilizing changes to your repo.

Either of this options would shield your plugin users from unexpected changes that could be made to the master branch of cordova-plugin-inappbrowser upstream.

**Comment by inderpreet-singh** [comment]
Thanks for updating it makes sense as using the HEAD branch will cause stability issue, so now we have forked the repository(https://github.com/appMobiGithub/cordova-plugin-appmobi/commit/bc031d3ec32f60d8872c00626afb7172593df188) and are using the same as a dependency until we have an npm update.

**Comment by tony--** [comment]
I see your update.  I have a few more suggestions about how to do this since you are depending on your fork.

1. currently you are pointing to a fork under inderpreet-singh account - it would be better if it was under appMobiGithub account for consistency.
2. add a note to README explaining why you are pointing to this fork instead of to the official version, otherwise some users will be suspicious that you are doing something sneaky.

**Comment by inderpreet-singh** [comment]
Thanks for the feedback, we have (1) updated the [fork](https://github.com/appMobiGithub/cordova-plugin-appmobi/commit/4b11fdbcbd9ba09fd5b6fce36e5f6ddfa804429a) with appMobiGitHub account and (2) added note in [ReadMe](https://github.com/appMobiGithub/cordova-plugin-appmobi/commit/fa203d91a7ca8b4b71d66ad8165bd3e95ac5a5fa) mentioning the forked repository

**Comment by tony--** [comment]
Thanks @inderpreet-singh - LGTM!
