### ISSUE TITLE
signup link listed in plugin.xml is currently a 404

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/cordova-plugin-appmobi#13]
https://cloud.appmobi.com/signup/

**Comment by stutzman29** [comment]
Thanks Tony, we will fix that asap. I think Ben was planning on doing a redirect for it, but it is redundant and will add the real link in asap.

**Comment by bwebsterdv** [comment]
Was this the most recent pull?  I had fixed this already in the latest commit I believe.  See https://github.com/appMobiGithub/cordova-plugin-appmobi/commit/19d373dd6203009368f17b19ef6fba3dcd0d20ec

**Comment by tony--** [comment]
Ah, I see - you switched it to https://cloud.appmobi.com/ and there is a "Create an account" button on that page.  My mistake (I was looking for the direct link that @stutzman29 had provided).

I'll close this.
