### ISSUE TITLE
support Crosswalk

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/cordova-plugin-appmobi#14]
Currently this plugin is not compatible with Crosswalk - adding the plugin to a Crosswalk app will result in the app crashing on startup.
I haven't debugged in order to identify root cause, but I think it is because both Crosswalk and the Appmobi plugin want to be the webview:

```
<preference name="webview" value="com.appMobiCloud.AppMobiWebViewEngine" />
```

This issue is important in the context of Intel XDK, because starting in the most recent EA release, Crosswalk will be the default when a user builds for Android (currently these are treated as separate build targets).  The user can disable this by unselecting "Optimize with Crosswalk", but it would be best if this plugin worked with Crosswalk.

That being said, I'm not sure how this can be done, since this plugin wants to override the webview interfaces and Crosswalk also overrides the webview interfaces.  It might be possible to wrap Crosswalk as needed and then extend the plugin with switching logic that would use the Crosswalk wrapper classes when the user is using Crosswalk.  I'm not sure if this is possible, though.

Another option might be to not attempt to provide seamless interoperability - just provide a Crosswalk-specific version of the plugin that is intended to be used in place of the Crosswalk plugin.  This would be less seamless in Intel XDK but would be a reasonable step in the right direction.

**Comment by rwvandenberg** [comment]
Hi @tony--,

I'm extremely sorry that the team left an Appmobi O.G. like yourself hanging on this issue. I've recently been deployed to this team and found this open issue.

Are you still a Crosswalk user? If so, would you be willing to see if the latest plugin still has the same issues you described above?

I'm unfamiliar with Crosswalk and haven't been able to quickly find any users within my circles.

Thanks,
Ryan Vandenberg

**Comment by tony--** [comment]
@rwvandenberg Thanks for following up!  [Crosswalk is no longer being maintained](https://crosswalk-project.org/blog/crosswalk-final-release.html) so this is no longer relevant and can be closed.
