### ISSUE TITLE
Start versioning releases

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/cordova-plugin-appmobi#2]
There are several pieces to versioning, suggest you start doing all of them.
1. add a RELEASENOTES.md, see cordova plugin for example:
https://github.com/apache/cordova-plugin-inappbrowser/blob/master/RELEASENOTES.md
2. add version tags for each release, e.g. here is version 1.0.1 of the cordova in app browser plugin
https://github.com/apache/cordova-plugin-inappbrowser/tree/r1.0.1
3. update the version in plugin.xml, add an entry to RELEASENOTES.md and tag the release all at the same time

Also consider doing the above versioning steps in conjunction with a release to npm.

**Comment by bwebsterdv** [comment]
1.0.0 added as initial release, Inder can you create a release tag or let me know which commit hook corresponds to 1.0.0 and I'll make the tag (https://github.com/appMobiGithub/cordova-plugin-appmobi/releases/new ) ?

**Comment by inderpreet-singh** [comment]
We have created the Initial Release for Appmobi Secure Platform [v1.0.0](https://github.com/appMobiGithub/cordova-plugin-appmobi/tree/v1.0.0)

**Comment by tony--** [comment]
Thanks
