### ISSUE TITLE
Only include working platforms in released versions?

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/cordova-plugin-appmobi#3]
I'm not sure of the best way to handle this.  This is a little tricky and depends on whether the plugin is intended for use with Intel XDK exclusively or for general usage.

Somehow, we need to let users know which platforms will work in the Intel XDK.
For example, the iOS platform will not work until Intel XDK adds support for cordova-ios 4.0+, which will not happen until sometime after cordova-ios 4.0 is released (at the time of this writing it has not been released).
One way this could be done is via the list of supported platforms in plugin.xml.
Another way could be by updating the information in README.md.

**Comment by tony--** [comment]
Mentioning @xmnboy for visibility and input.

**Comment by inderpreet-singh** [comment]
This plugin will work with both, either through cordova CLI or Intel XDK but both has iOS version dependency of ‘>=4.0.0’ Thanks for bringing the issue, our iOS compatibility check needs to be integrated which was missing. We will be adding below compatibility check in plugin.xml  :
```
<engine name="cordova-ios" version=">=4.0.0-dev" />
```
We tested with the above in IntelXDK locally and were not able to build for iOS using this update. So this seems to be a valid approach for compatibility check, any thoughts? We are also in process of updating ReadMe.md having supported platform details and will be doing so shortly

**Comment by tony--** [comment]
Adding the _engine_ compatibility flag is a good step for the general case.
If README.md also includes a compatibility section, this seems like it would cover the issue to me.
@xmnboy - thoughts?

**Comment by stutzman29** [comment]
Ben, see @tony-- comment about adding to the README.md

**Comment by bwebsterdv** [comment]
Added to README

**Comment by bwebsterdv** [comment]
Leaving open actually in case of other edits

**Comment by tony--** [comment]
Thanks for the updates.  Suggested edit:
iOS (For Intel XDK the plugin will not work for iOS as it has dependency on **cordova** v4.0.0 which has not been released yet.)
-->
iOS (For Intel XDK the plugin will not work for iOS as it has dependency on **cordova-ios** v4.0.0 which has not been released yet.)

**Comment by inderpreet-singh** [comment]
We have updated the Readme.md file with the mentioned suggestion (**cordova** -> **cordova-ios**)

**Comment by tony--** [comment]
Thanks
