### ISSUE TITLE
consider updating plugin id to match newer cordova naming convention

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/cordova-plugin-appmobi#4]
Currently the id of the plugin is "com.appMobiCloud" (as defined in plugin.xml).
All of the Cordova core plugins have been renamed to use a '-' naming convention for consistency with npm modules instead of a '.' naming convention, e.g., "org.apache.cordova.inappbrowser" has been changed to "cordova-plugin-inappbrowser".
Consider changing the id of this plugin to something like "cordova-plugin-appmobi" or "cordova-plugin-appmobi-cloud".

**Comment by inderpreet-singh** [comment]
We have updated the ID of the plugin to "cordova-plugin-appmobi" as suggested

**Comment by tony--** [comment]
Thanks.
