### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/cordova-plugin-appmobi#5]
Currently README.md does not have any content.  
It should be updated with a description of the plugin and information about how to use the plugin.   
Refer to Cordova core plugin READMEs for reference, e.g.:
https://github.com/apache/cordova-plugin-inappbrowser/blob/master/README.md

**Comment by tony--** [comment]
Also consider linking to the Appmobi sample app from the README.md.

**Comment by bwebsterdv** [comment]
Sample project linked on README

**Comment by tony--** [comment]
README is looking a lot better - might want to get a second set of eyes to proofread (for example, I noticed "Appmobi Sample Cordova Application *Tempalte*" when I scanned over it).
Will leave this open until we get the new name for APP_SECRET and update in README...

**Comment by tony--** [comment]
I just realized another thing about the README - this copy seems ok for the sample, but in order to conform to best practices, the plugin README should include documentation for the APIs.  I guess you could also retain the descriptive text, but you should add API documentation.
Please refer to Cordova core plugin READMEs for reference, e.g.:
https://github.com/apache/cordova-plugin-inappbrowser/blob/master/README.md

**Comment by inderpreet-singh** [comment]
Thanks for the feedback, we have now included API documentation in the ReadMe.md file.

**Comment by tony--** [comment]
Thanks, closing!
