### ISSUE TITLE
need feed metadata for Intel XDK integration

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/cordova-plugin-appmobi#6]
The title and description are hardcoded metadata in the Intel XDK feed.
If README.md is updated with a description at the top of the file, that could be manually added into the feed.
An alternative would be to make a separate file that lists the feed metadata (title and description) explicitly.
However the metadata is provided, integrating it into the feed is a manual step - it is not directly ingested from any of the files in the repo.

**Comment by bwebsterdv** [comment]
README now has the first paragraph with a description, is there another edit necessary or other change needed now?  Thanks!

**Comment by tony--** [comment]
@bwebsterdv - I guess if I combine the first paragraph with the sentence from requirements it would work?  We need to make it clear that an Appmobi account is a prereq to trying to sample.

**Comment by tony--** [comment]
Here is what I am using, based on discussion with @bwebsterdv (partially cribbed from README, note that I had to insert some formatting to accomodate the placement - we can tweak it as needed):
name: Appmobi Secure Mobile Platform
description: 
```
          <p class="feedPluginTitle">Appmobi* Secure Mobile Platform by Appmobi</p>
          <p>Appmobi Secure Mobile Platform provides a level of security never seen in a mobile platform, enabling the 
          development of highly secure Cordova-based applications in minutes versus months. This platform provides 
          your development team with configurable, high-performance security options for every app built, including 
          app and device level shared keys for encryption and identity verification as well as integration with 
          most 3rd party authentication systems such as OAUTH, LDAP, and more.
          Quickly and easily build the most secure apps on the market today, in minutes.

          In order to utilize the Appmobi platform you must have a registered Appmobi PrivateStack platform. 
          If you do not have an account or Appmobi PrivateStack server you can <a href="https://licensing.appmobi.com/demo/signup/">Register for a Demo on our website</a>.
          </p>
          <p>Please refer to the plugin documentation link for API details, supported platforms and required variables.</p>
```
