### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/cordova-plugin-appmobi#7]
e.g., https://github.com/apache/cordova-plugin-inappbrowser/blob/master/LICENSE

Might need to customize that to have Appmobi copyright...

**Comment by bwebsterdv** [comment]
Added to repo

**Comment by tony--** [comment]
Great!  
Maybe a nitpick, but since it's named LICENSE.md, it shows as markdown when you view it on github.  Since it is really plaintext it looks a little weird.  For comparison, the Apache Cordova license files are all called LICENSE so they are displayed as plaintext when viewed on github, e.g.:
https://github.com/apache/cordova-plugin-inappbrowser/blob/master/LICENSE

Thought it was worth calling out the above, but it's there and that's the main thing, so I'm closing this.
