### ISSUE TITLE
update plugin to depend on cordova-plugin-inappbrowser 1.1.1 when it is released

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/cordova-plugin-appmobi#8]
This issue cannot be addressed until cordova-plugin-inappbrowser 1.1.1 is released - the release vote is underway now and barring any issues, it should pass today.

This release will include a fix for [CB-10040](https://issues.apache.org/jira/browse/CB-10040), which is the blocker bug that caused this plugin to depend on a fork of cordova-plugin-inappbrowser.

Refer to https://issues.apache.org/jira/browse/CB-10187 for more information.

**Comment by inderpreet-singh** [comment]
Thanks for the feedback, we checked the provided link and this seems to solve blocker bug [CB-10040](https://issues.apache.org/jira/browse/CB-10040) we were having. So we suggest now to update the dependency tag and refer to this specific commit instead of fork as below, Any thoughts?
```
<dependency id="cordova-plugin-inappbrowser" url="https://github.com/apache/cordova-plugin-inappbrowser" commit="ce285e8e0635173f3e5314a4a960db1180611fde"/>
```

**Comment by tony--** [comment]
I don't think you should refer to the specific commit.  Instead (after cordova-plugin-inappbrowser 1.1.1 is released, probably later today) you should be able to switch to a regular dependency:
<dependency id="cordova-plugin-inappbrowser@1.1.1" />
or even just
<dependency id="cordova-plugin-inappbrowser" />

You should also bump the version of this plugin when you make this change.

**Comment by tony--** [comment]
[cordova-plugin-inappbrowser 1.1.1 has been released](https://www.npmjs.com/package/cordova-plugin-inappbrowser), so this issue can be resolved now.

**Comment by inderpreet-singh** [comment]
Thanks for the update, we have [updated](https://github.com/appMobiGithub/cordova-plugin-appmobi/commit/ae75968a541d6532960eed6c844c18161c97b943) our plugin dependency to use the latest release 1.1.1 of InAppBrowser plugin

**Comment by tony--** [comment]
Sorry, I was mistaken about the required syntax.
The following will result in the wrong version of cordova-plugin-inappbrowser being included when cordova-plugin-appmobi is added to a project in Intel XDK:
`<dependency id="cordova-plugin-inappbrowser" />`
This is because when the version is not specified, the latest version from the feed is used.

In order to include a version that is not included in the Intel XDK plugin feed, the version must be explicit:
`<dependency id="cordova-plugin-inappbrowser@1.1.1" />`

**Comment by tony--** [comment]
If you decide to merge in this PR, you'll need to move the v1.0.2 tag or create a new tag.

**Comment by inderpreet-singh** [comment]
Thanks for the feedback, we have merged the PR and are now using explicit version 1.1.1 as suggested. Also, we have moved the tag [v1.0.2](https://github.com/appMobiGithub/cordova-plugin-appmobi/tree/v1.0.2) with the updated merge request.

**Comment by tony--** [comment]
Thanks
