### ISSUE TITLE
For the version tagged as v1.0.1, the version string in plugin.xml is 1.0.0

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/cordova-plugin-appmobi#9]
[The commit that bumps the version string](https://github.com/appMobiGithub/cordova-plugin-appmobi/commit/e9944337871feb97241fbbcc626befb02132b98a) is after [the commit that is tagged](https://github.com/appMobiGithub/cordova-plugin-appmobi/commit/39b7ea32be2beb988256fc5455ebb9ca4ed0e962).

**Comment by inderpreet-singh** [comment]
We have updated the release tag v1.0.1 with required plugin.xml changes

**Comment by tony--** [comment]
Thanks
